name: trackbudi_mobile
description: TrackBudi is a logistic application

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  ionicons: ^0.2.2

  #Networking
  retrofit: ^3.3.0
  dio: ^4.0.6
  jwt_decoder: ^2.0.1
  dartz: any
  rxdart: ^0.27.3

  #State Management
  flutter_riverpod: ^1.0.4
  provider:
  hooks_riverpod:

  #Others
  flutter_hooks: ^0.18.5+1
  file_picker:
  intl:
  get_it: ^7.2.0
  # floor: ^1.4.1
  equatable: ^2.0.5
  injectable: ^1.5.0
  logger: ^1.4.0
  pinput: ^2.2.31
  camera: ^0.10.3
  geolocator: ^9.0.2
  intl_phone_number_input: ^0.7.3+1
  intl_phone_field: ^3.1.0
  country_calling_code_picker:
  image_picker: ^0.8.6+1
  country_picker: ^2.0.20
  qr_flutter: ^4.0.0
  local_auth: ^1.1.10
  permission_handler: ^10.2.0
  timeago: ^3.3.0
  formz: ^0.4.1
  dropdown_search: ^5.0.6
  awesome_dio_interceptor: ^0.0.2+4
  auto_route: ^5.0.4
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^8.0.0
  decimal: ^2.2.0
  json_annotation:
  freezed_annotation: ^2.0.1
  money_formatter: ^0.0.3
  flutter_svg: ^1.1.6
  flutter_sizer: ^1.0.4
  dots_indicator: ^3.0.0
  fluttertoast: ^8.2.2
  pin_code_fields: ^7.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.0.1
  auto_route_generator: ^5.0.3
  retrofit_generator: ^4.1.2
  # floor_generator: ^1.4.1
  build_runner: ^2.3.3
  flutter_gen: any
  flutter_gen_runner:
  freezed: ^2.3.2
  json_serializable: any
  injectable_generator: any

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/svgs/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Euclad
      fonts:
        - asset: assets/fonts/Euclid_Circular_A_Regular.ttf
        - asset: assets/fonts/Euclid_Circular_A_Bold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
